spring.application.name=zero
spring.datasource.url=jdbc:postgresql://localhost:5432/zero
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


